import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import { useEffect, useState } from 'react'
import axios from 'axios'
import Link from 'next/link'



export default function Home() {

  const [data, setData] = useState();

  const apiKey = "5RN7lkbb1E4ZmerExI7a0zQxfBbMGlGZCmcpM94s"
  const url = `https://api.nasa.gov/techtransfer/patent/?engine&api_key=${apiKey}`

  const getTechTransferforData = async () => {
    const res = await axios.get(url);
    const info = await res.data;
    console.log(info);
    setData(info);
  }

  useEffect(() => {
    getTechTransferforData();
  }, [])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Link href="/polychromatic" className={styles.link}>polychromatic ➜</Link>
      <main className={styles.mainGallery}>
        {
          data && data.results.map((tech, index) => {
            return (

              <div key={index}>
                {
                  tech && tech.map((t, ind) => {
                    if (ind === 10) {
                      return (
                          <Image src={t} alt={t} key={ind} width={200} height={200} />
                      )
                    }
                  })
                }
              </div>
            )
          })
        }
      </main>
    </>
  )
}
